fifo: fifo.cpp utils.cpp utils.h
	g++ -o fifo fifo.cpp utils.cpp

random: random.cpp utils.cpp utils.h
	g++ -o random random.cpp utils.cpp

lru: lru.cpp utils.cpp utils.h
	g++ -o lru lru.cpp utils.cpp

clean: fifo random lru
	rm fifo random lru

all: fifo random lru